#!/bin/bash

EMOJI_FILE="$HOME/.cache/emojis.txt"

URLS=(
    'https://emojipedia.org/people/'
    'https://emojipedia.org/nature/'
    'https://emojipedia.org/food-drink/'
    'https://emojipedia.org/activity/'
    'https://emojipedia.org/travel-places/'
    'https://emojipedia.org/objects/'
    'https://emojipedia.org/symbols/'
    'https://emojipedia.org/flags/'
)

function download(){
    
    notify-send "Rofi" "Refreshing emoji cache in $EMOJI_FILE..."
    touch "$EMOJI_FILE"
    
    for url in "${URLS[@]}"; do
        
        # download the list of emoji and remove all the junk around it
        emojis=$(curl -s "$url" | \
                 xmllint --html \
                         --xpath '//ul[@class="emoji-list"]' - 2>/dev/null)
        
        # get rid of starting/closing ul tags
        emojis=$(echo "$emojis" | head -n -1 | tail -n +1)
        
        # extract the emoji and its description
        emojis=$(echo "$emojis" | \
                 sed -rn 's/.*<span class="emoji">(.*)<\/span> (.*)<\/a><\/li>/\1 \2/p')
        
        # prepend "0 " as frequency count
        echo "$emojis" | sed 's/^/0 /' >> "$EMOJI_FILE"
        
    done
    
    notify-send "Rofi" "Done"
    
}

if [[ -z "$@" ]]; then
    
    # download the emojis if not cached
    [[ ! -f "$EMOJI_FILE" ]] && download
    
    # send emojis to rofi (cut the frequencies)
    cat "$EMOJI_FILE" | cut -d' ' -f 2-
    
else
    
    # increment frequency count of selected line 
    # in cache and sort by frequency ONLY
    cat "$EMOJI_FILE"                                    | \
    sed -r "s/([0-9]+) ($*)/echo \"\$((\\1+1)) \\2\"/ge" | \
    sort -r -s -n -k 1,1 -o "$EMOJI_FILE"
    
    # get the emoji from the picked line and put it in the clipboard
    echo "$*" | awk '{print $1}' | tr -d '\n' | xsel -i -b
    
fi
