#!/bin/bash

swaylock --screenshots \
         --clock \
         --indicator \
         --indicator-radius 90 \
         --indicator-thickness 7 \
         --effect-blur 12x8 \
         --text-color ebecef \
         --line-color ebecef \
         --key-hl-color cc4f32 \
         --ring-color 11111bbb \
         --inside-color 11111bbb \
         --inside-clear-color eff0ee \
         --separator-color 00000000 \
         --fade-in 0
