#!/bin/bash

swaylock --screenshots --clock \
	 --indicator \
         --indicator-radius 80 \
         --indicator-thickness 5 \
         --effect-blur 12x8 \
         #--effect-vignette 0.5:0.5 \
         --ring-color 11111b \
         --line-color 313244 --inside-color 0011111b --separator-color 00000000 --fade-in 2 &

