#!/bin/bash

pamixer --default-source -t

if [ $(pamixer --default-source --get-mute) == "true" ]; then
    notify-send -h string:x-dunst-stack-tag:mic "Microphone" "Microphone muted"
else
    notify-send -h string:x-dunst-stack-tag:mic "Microphone" "Microphone unmuted"
fi
