#!/bin/bash

pamixer $@

volume=$(pamixer --get-volume)

if (( $volume <= 25 )); then
    symbol=""
elif (( "$volume" <= 50 )); then
    symbol=""
elif (( "$volume" <= 75 )); then
    symbol=""
else
    symbol=""
fi

[[ $(pamixer --get-mute) == "true" ]] && muted=" (Muted)"

dunstify -h string:x-dunst-stack-tag:volume "$symbol Volume control" "Volume at $volume%$muted"
