#! /bin/sh

desktops=6 # spreads the desktops across available monitors

i=1
monitors=$(bspc query -M)
num_monitors=$(wc -l <<< $monitors)
dpm=$((desktops/num_monitors))

for m in $monitors; do
    
    seq $i $((i+dpm-1)) | xargs bspc monitor $m -d
    ((i+=dpm))
    
done

# bspc monitor HDMI-0 -d 1 2 3
# bspc monitor DP-0 -d 4 5 6

bspc config ignore_ewmh_focus             true
bspc config borderless_monocle            true
bspc config gapless_monocle               true

bspc config border_width                  3
bspc config window_gap                    36

bspc config split_ratio                   0.50
bspc config top_padding                   0

# 1 > web / misc
bspc rule -a Google-chrome                desktop='^1'
bspc rule -a Firefox                      desktop='^1'

# 2 > terminal
bspc rule -a Alacritty                    desktop='^2'   follow=on

# 3 > media
bspc rule -a Spotify                      desktop='^3'
bspc rule -a discord                      desktop='^3'

# 4 > code
bspc rule -a Subl3                        desktop='^4'
bspc rule -a jetbrains-pycharm            desktop='^4'
bspc rule -a jetbrains-intellij           desktop='^4'
bspc rule -a jetbrains-clion              desktop='^4'
bspc rule -a jetbrains-webstorm           desktop='^4'

# misc
bspc rule -a Gimp                         state=floating follow=on
bspc rule -a Screenkey manage=off

# floaty bois
bspc rule -a feh                          state=floating
bspc rule -a mpv                          state=floating
bspc rule -a Pamac-manager                state=floating
bspc rule -a Gcolor3                      state=floating
bspc rule -a Gnome-calendar               state=floating
bspc rule -a Alacritty:Alacritty_floating state=floating follow=on desktop='^-1'

# fix java assuming reparenting windows with swing
export _JAVA_AWT_WM_NONREPARENTING=1

# set cursor and background
xsetroot -cursor_name left_ptr
feh --no-fehbg --bg-scale ~/.wallpapers/cat.jpg

# disable screensaver
xset -dpms
xset s off
xset s noblank

# start compton
compton -cb

# start sxhkd
killall -9 sxhkd; sxhkd &
