#!/bin/bash

# start polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

xrdb -q
xrdb -merge ~/.Xresources

# start sxhkd
killall -9 sxhkd; sxhkd &

# disable regular caps lock functionality
# but is rebound to start rofi in sxhkdrc
setxkbmap -symbols 'pc+dk+capsoff'

# top level settings
bspc config ignore_ewmh_focus             true
bspc config borderless_monocle            true
bspc config gapless_monocle               true

bspc config focused_border_color          "#E8E4C9"
bspc config normal_border_color           "#4D4D4B"
bspc config active_border_color           "#4D4D4B"

bspc config border_width                  2
bspc config window_gap                    30

bspc config top_padding                   12
bspc config bottom_padding                12
bspc config top_monocle_padding          -12
bspc config bottom_monocle_padding       -12

bspc config split_ratio                   0.50

bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true

desktops=10

# GET ACTIVE OUTPUTS FROM XRANDR
# xrandr | grep -E " connected (primary )?[1-9]+" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/"

# GET CONNECTED OUTPUTS FROM XRANDR
# xrandr | grep " connected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/"

configure_desktops(){
    
    monitors=$(bspc query -M)
    num_monitors=$(wc -l <<< $monitors)
    dpm=$((desktops/num_monitors))
    
    i=1
    
    for m in $monitors; do
        
        seq $i $((i+dpm-1)) | xargs bspc monitor $m -d
        ((i+=dpm))
        
    done
    
    # set wallpaper
    feh --no-fehbg --bg-scale --no-xinerama ~/.wallpapers/cesar329.jpg
    
    # spotify rule doesn't work, spotifys fault
    bspc rule -a spotify            desktop="^$(~/.config/bspwm/map_desktop $num_monitors 3)"
    bspc rule -a discord            desktop="^$(~/.config/bspwm/map_desktop $num_monitors 3)"
    
    bspc rule -a jetbrains-pycharm  desktop="^$(~/.config/bspwm/map_desktop $num_monitors 4)"
    bspc rule -a jetbrains-intellij desktop="^$(~/.config/bspwm/map_desktop $num_monitors 4)"
    bspc rule -a jetbrains-clion    desktop="^$(~/.config/bspwm/map_desktop $num_monitors 4)"
    bspc rule -a jetbrains-webstorm desktop="^$(~/.config/bspwm/map_desktop $num_monitors 4)"
    
}

configure_desktops

# reconfigure desktops when the monitor configuration changes
# TODO: send desktops to correct new map_desktop locations!
bspc subscribe monitor | while read -r line; do
    ([[ $line == monitor_add* ]] || [[ $line == monitor_remove* ]]) && configure_desktops
done &

# floaty bois
bspc rule -a feh                          state=floating follow=on
bspc rule -a mpv                          state=floating follow=on
bspc rule -a Pamac-manager                state=floating
bspc rule -a File-roller                  state=floating
bspc rule -a Gcolor3                      state=floating
bspc rule -a Gnome-calendar               state=floating
bspc rule -a "Blueberry.py"               state=floating
bspc rule -a WebTorrent                   state=floating
bspc rule -a Gimp                         state=floating follow=on
bspc rule -a term_floating                state=floating follow=on

# set cursor
xsetroot -cursor_name left_ptr

# start libinput-gestures if its installed
[[ -x $(which libinput-gestures-setup) ]] && libinput-gestures-setup start &

# start thunar daemon for quicker launch
thunar --daemon &

# start compton
compton &

# start clipboard manager
parcellite &

# start redshift (night light)
redshift &

# disable screensaver
xset -dpms
xset s off
xset s noblank