#! /bin/sh

bspc monitor HDMI-0 -d I II III
bspc monitor DP-0 -d IV V VI

bspc config border_width        3
bspc config window_gap          36

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config top_padding         0

# 1 > web / misc
bspc rule -a Google-chrome      desktop='^1'
bspc rule -a Firefox            desktop='^1'

# 2 > terminal
bspc rule -a Alacritty          desktop='^2'

# 3 > media
bspc rule -a Spotify            desktop='^3'
bspc rule -a discord            desktop='^3'

# 4 > code
bspc rule -a Subl3              desktop='^4'
bspc rule -a jetbrains-pycharm  desktop='^4'
bspc rule -a jetbrains-intellij desktop='^4'
bspc rule -a jetbrains-clion    desktop='^4'
bspc rule -a jetbrains-webstorm desktop='^4'

# misc
bspc rule -a Gimp state=floating follow=on
bspc rule -a Screenkey manage=off

# floaty bois
bspc rule -a feh           state=floating
bspc rule -a mpv           state=floating
bspc rule -a Pamac-manager state=floating
bspc rule -a Gcolor3       state=floating

# fix java assuming reparenting windows with swing
export _JAVA_AWT_WM_NONREPARENTING=1

# set cursor and background
xsetroot -cursor_name left_ptr
feh --no-fehbg --bg-scale ~/.wallpapers/cat.jpg

# disable screensaver
xset -dpms
xset s off
xset s noblank

# start compton
compton -cb

# start sxhkd
killall -9 sxhkd; sxhkd &
