os:
  edit:              'hx -- {{filename}}'
  editAtLine:        'hx -- {{filename}}:{{line}}'
  editAtLineAndWait: 'hx -- {{filename}}:{{line}}'
  openDirInEditor:   'hx -- {{dir}}'
  editInTerminal:    true

git:
  paging:
    colorArg: always
    pager: delta --paging=never --features="falkaer compact"
