os:
  edit:              'hx -- {{filename}}'
  editAtLine:        'hx -- {{filename}}:{{line}}'
  editAtLineAndWait: 'hx -- {{filename}}:{{line}}'
  openDirInEditor:   'hx -- {{dir}}'
  editInTerminal:    true
