indentation = 2
seperate-label = true
final-newline = true

[preserve-newline]
content = false
math = false

[block]
long-block-style = "compact"

[term]
space-before = false
space-after = true

[named-argument]
space-before = false
space-after = true

[dictionary-entry]
space-before = false
space-after = true

[import-statement]
space-before = false
space-after = true

[comma]
space-before = false
space-after = true

[columns]
comma = "end-of-content"

[heading]
blank-lines-before = 1
blank-lines-after = 0

[columns-methods]
tablex = "columns"
gridx = "columns"
grid = "columns"
table = "columns"
