# SPELL CHECKER
[language-server.typos]
command = "typos-lsp"
config.diagnosticSeverity = "Warning"

# PROGRAMMING LANGUAGES

# pyright, ruff-lsp
[[language]]
name = "python"
language-servers = ["pyright", "ruff"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[language-server.pyright.config.pyright]
disableOrganizeImports = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

# golines, goimports, gopls, golangci-lint-lsp
[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint-lsp"]

[language.formatter]
command = "golines"
args = [
  "--base-formatter",
  "goimports",
  "--max-len",
  "88",
  "--chain-split-dots",
]

# bash-language-server, shfmt
[[language]]
name = "bash"
language-servers = ["bash-language-server"]

[language.formatter]
command = "shfmt"
args = ["-s", "-ci", "-sr", "-kp", "-bn", "-i", "2"]

# TODO: add C/C++/CUDA stuff explicitly

# typescript, javascript, json formatter
[language-server.biome]
command = "bash"
args = ["-c", "lsp-proxy --config-path ~/.config/biome.json"]

# typescript-language-server, biome
[[language]]
name = "javascript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

# https://github.com/helix-editor/helix/discussions/8987
# biome lsp-proxy doesn't work properly, this workaround works for now
[language.formatter]
command = "bash"
args = [
  "-c",
  "biome format --config-path ~/.config/biome.json --stdin-file-path a.js",
]

# typescript-language-server, biome
[[language]]
name = "typescript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

# https://github.com/helix-editor/helix/discussions/8987
# biome lsp-proxy doesn't work properly, this workaround works for now
[language.formatter]
command = "bash"
args = [
  "-c",
  "biome format --config-path ~/.config/biome.json --stdin-file-path a.ts",
]

# WORD PROCESSORS (LATEX / TYPST) 

# texlab, tectonic, latexindent, typos-lsp
[[language]]
name = "latex"
language-servers = ["texlab", "typos"]

[language-server.texlab.config.texlab]
diagnosticsDelay = 0

[language-server.texlab.config.texlab.latexindent]
# config is at ~/.config/latexindent/config.yaml
modifyLineBreaks = true

# NB: this won't compile unless the out directory already exists
[language-server.texlab.config.texlab.build]
onSave = true
executable = "tectonic"
args = [
  "-X",
  "compile",
  "%f",
  "-o",
  "out",
  "--synctex",
  "--keep-logs",
  "--keep-intermediates",
]
auxDirectory = "out"
logDirectory = "out"
pdfDirectory = "out"
forwardSearchAfter = true

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = ["--synctex-forward", "%l:1:%f", "%p"]

[language-server.texlab.config.texlab.chktex]
onEdit = true

# tinymist, typstfmt, prettypst, typos-lsp
[[language]]
name = "typst"
language-servers = ["tinymist", "typos"]

[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "onSave" }

[language.formatter]
command = "bash"
args = [
  "-c",
  "typstfmt --output - | prettypst --file-location ~/.config/prettypst.toml --use-std-in --use-std-out",
]

# PLAINTEXT / CONFIG LANGUAGES

# marksman, markdown-oxide, mdformat, typos-lsp
[[language]]
name = "markdown"
language-servers = ["marksman", "markdown-oxide", "typos"]

[language.formatter]
command = "mdformat"
args = ["--wrap", "88", "-"]

# taplo, typos
[[language]]
name = "toml"
language-servers = ["taplo", "typos"]

[language.formatter]
command = "taplo"
args = ["format", "-"]

# yaml-language-server, prettier, typos-lsp
[[language]]
name = "yaml"
language-servers = ["yaml-language-server", "typos"]

[language.formatter]
command = "prettier"
args = ["--parser", "yaml"]

# vscode-json-language-server, biome
[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]
auto-format = false

# https://github.com/helix-editor/helix/discussions/8987
# biome lsp-proxy doesn't work properly, this workaround works for now
[language.formatter]
command = "bash"
args = [
  "-c",
  "biome format --config-path ~/.config/biome.json --stdin-file-path a.json",
]

[[language]]
name = "kdl"
indent = { tab-width = 4, unit = "    " }
