[[language]]
name = "python"
language-servers = ["pyright", "ruff"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[language-server.pyright.config.pyright]
disableOrganizeImports = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[[language]]
name = "bash"

[language.formatter]
command = "shfmt"
args = ["-s", "-ci", "-sr", "-kp", "-bn", "-i", "2"]

[[language]]
name = "toml"

[language.formatter]
command = "taplo"
args = ["format", "-"]

[[language]]
name = "typst"

# [language.formatter]
# command = "typstfmt"
# args = ["--output", "-"]

[language.formatter]
command = "prettypst"
args = [
  "--file-location",
  "~/.config/prettypst.toml",
  "--use-std-in",
  "--use-std-out",
]

[[language]]
name = "latex"
language-servers = ["texlab"]

[language-server.texlab.config.texlab]
diagnosticsDelay = 0

[language-server.texlab.config.texlab.latexindent]
modifyLineBreaks = true

[language-server.texlab.config.texlab.build]
onSave = true
executable = "tectonic"
args = [
  "-X",
  "compile",
  "%f",
  "-o",
  "out",
  "--synctex",
  "--keep-logs",
  "--keep-intermediates",
]
auxDirectory = "out"
logDirectory = "out"
pdfDirectory = "out"
forwardSearchAfter = true

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = ["--synctex-forward", "%l:1:%f", "%p"]

[language-server.texlab.config.texlab.chktex]
onEdit = true

[[language]]
name = "kdl"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "yaml"
language-servers = ["yaml-language-server"]

[language.formatter]
command = "prettier"
args = ["--parser", "yaml"]
