[[language]]
name = "python"
language-servers = ["pyright", "ruff"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[language-server.pyright.config.pyright]
disableOrganizeImports = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

# TODO: shfmt as shell formatter

[[language]]
name = "toml"

[language.formatter]
command = "taplo"
args = ["format", "-"]

# [[language]]
# name = "typst"
# formatter = { command = "typstfmt", args = ["--output", "-"] }

[[language]]
name = "kdl"
indent = { tab-width = 4, unit = "    " }
