defaultIndent: "    "

indentPreamble: 1
lookForAlignDelims:
  caption: 1

removeTrailingWhitespace: 1
noAdditionalIndent:
  abstract: 1

modifyLineBreaks:
  preserveBlankLines: 1
  condenseMultipleBlankLinesInto: 1
  mandatoryArguments:
    caption:
      MandArgBodyStartsOnOwnLine: 1
      RCuBStartsOnOwnLine: 1
  textWrapOptions:
    columns: 88
    multipleSpacesToSingle: 1
    comments:
      wrap: 0
    when: after
    blocksFollow:
      other: '\\\]|\\item(?:\h|\[)|\\caption\h*(?:\[\])?\h*\{'
    blocksBeginWith:
      0-9: 1
      # in general we can't say if a command counts as part of a sentence block,
      # so it has to be a whitelist
      # \Gls, \gls, \Cref, \text..., inline math, etc. can start sentence blocks
      other: '\\Gls|\\gls|\\Cref|\\text|\\noindent|\\footnote|\$'
    blocksEndBefore:
      other: '\\\[|\\begin\{|\\end\{'
