defaultIndent: "    "

modifyLineBreaks:
  textWrapOptions:
    columns: 88
    comments:
      wrap: 0
    blocksFollow:
      other: '\\\]|\\item(?:\[.*\])?|\\begin\{.+\}|\\end\{.+\}'
    blocksBeginWith:
      # in general we can't say if a command counts as part of a sentence block,
      # so it has to be a whitelist
      # \Gls, \gls, \Cref, \text..., inline math, etc. can start sentence blocks
      other: '\\(([gG]ls)|(Cref)|(text))|\$'
    blocksEndBefore:
      other: '\\\[|\\begin\{|\\end\{'
