defaultIndent: "    "

modifyLineBreaks:
  textWrapOptions:
    columns: 88
    comments:
      wrap: 1
    blocksBeginWith:
      # \Gls, \gls, \Cref, \text..., inline math, etc. can start sentence blocks
      other: '(\\(([gG]ls)|(Cref)|(text)))|(\$)'
