#!/bin/bash

# Start authentication and notification daemons
dbus-update-activation-environment --all
/usr/bin/gnome-keyring-daemon --start --components=secrets &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Night light
gammastep &

# Thunar daemon
thunar --daemon &

# Export wayland envs (???)
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Set wallpaper
~/.scripts/wallchange "$HOME/.wallpapers/wannabigsur.png"
