#!/bin/bash

# $1 is folder to search in, $2 is folder to place in
find "$1" -type f | while read file; do 
    
    # remove prefix
    name="${file#"$1/"}"
    target="$2/$name"
    
    mkdir -p "$(dirname "$target")"
    ln -sf "$file" "$target"
    
done
